# Enable BuildKit for faster builds
x-environment:
  &build-env
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

services:
  text-to-video:
    build: 
      context: .
      # This helps enable BuildKit when building this service
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - SUBTITLE_MAX_CHARS=${SUBTITLE_MAX_CHARS}
      - MAX_BG_VIDEOS=${MAX_BG_VIDEOS}
      - PHOTO_OUTPUT_DIR=${PHOTO_OUTPUT_DIR}
      - PEXELS_PHOTO_API_URL=${PEXELS_PHOTO_API_URL}
      - PEXELS_PHOTO_API_URL_CURATED=${PEXELS_PHOTO_API_URL_CURATED}
      - PEXELS_VIDEO_API_URL=${PEXELS_VIDEO_API_URL}
      - PEXELS_VIDEO_API_URL_CURATED=${PEXELS_VIDEO_API_URL_CURATED}
      - VOICE_PROVIDER=${VOICE_PROVIDER}
      - KOKORO_SERVICE_URL=${KOKORO_SERVICE_URL}
      - ELEVENLABS_SERVICE_URL=${ELEVENLABS_SERVICE_URL}
      - TIKTOK_SERVICE_URL=${TIKTOK_SERVICE_URL}
    ports:
      - "7701:7701"
    networks:
      - ttv-network
      - crown-network
    command: streamlit run streamlit_app.py --server.port=7701 --server.address=0.0.0.0

networks:
  ttv-network:
    driver: bridge
  crown-network:
    external: true
