services:
  app:
    container_name: reelsmaker 

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7501:7501"
    volumes:
      - ./:/app # for Dev: Mount the current directory to /app in the container
      - ./tmp:/app/tmp
      - ./images:/app/images
      - ./data:/app/data  # Mount the whole data directory instead
      - /dev/dri:/dev/dri  # Add this line to access the Intel GPU
    deploy:
      resources:
        limits:
          memory: 8G  # Add a resource limit to make the structure valid
    environment:      
      - BACKGROUND_MUSIC_PATH=/app/assets/music
      - BACKGROUND_MUSIC_ENABLED=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}      
      - VOICE_PROVIDER=kokoro  # Set default voice provider to Kokoro
      - KOKORO_SERVICE_URL=http://kokoro_service:8880  # URL for the service
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - MAX_BG_VIDEOS=${MAX_BG_VIDEOS}
      - SUBTITLE_MAX_CHARS=${SUBTITLE_MAX_CHARS}      
      # CPU optimization 
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - NUMEXPR_NUM_THREADS=8
      - PYTORCH_ENABLE_CPU_FALLBACK=1
      # FFmpeg optimization 
      - FFREPORT=file=/app/tmp/ffmpeg_report.log:level=32
      - AV_LOG_FORCE_COLOR=1
      - FFMPEG_THREADS=8
      # Intel GPU support Newer Intel GPUs (try for UHD)
      - LIBVA_DRIVER_NAME=iHD
      # Hardware acceleration flags for FFmpeg
      - FFMPEG_HWACCEL=vaapi
      - FFMPEG_VAAPI_DEVICE=/dev/dri/renderD128
    runtime: "runc"
    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    networks:
      reels-network:
        aliases:
          - reelsmaker
      crown-network:
        aliases:
          - reelsmaker
        
    command: >
      bash -c "
        streamlit run reelsmaker.py --server.port=7501 --server.address=0.0.0.0
      "

networks:
  reels-network:  
    driver: bridge
  crown-network:
    external: true